FROM golang:1.25-alpine AS builder

RUN apk add --no-cache git build-base

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

FROM alpine:latest

COPY --from=builder /go/bin/goose /bin/goose

WORKDIR /migrations

RUN apk add --no-cache bash
ENTRYPOINT ["/bin/goose"]