// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"context"
	"scrapper/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPostgres creates a new instance of MockPostgres. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostgres(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostgres {
	mock := &MockPostgres{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostgres is an autogenerated mock type for the Postgres type
type MockPostgres struct {
	mock.Mock
}

type MockPostgres_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostgres) EXPECT() *MockPostgres_Expecter {
	return &MockPostgres_Expecter{mock: &_m.Mock}
}

// AddLink provides a mock function for the type MockPostgres
func (_mock *MockPostgres) AddLink(ctx context.Context, link *domain.Link) error {
	ret := _mock.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for AddLink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Link) error); ok {
		r0 = returnFunc(ctx, link)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostgres_AddLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddLink'
type MockPostgres_AddLink_Call struct {
	*mock.Call
}

// AddLink is a helper method to define mock.On call
//   - ctx context.Context
//   - link *domain.Link
func (_e *MockPostgres_Expecter) AddLink(ctx interface{}, link interface{}) *MockPostgres_AddLink_Call {
	return &MockPostgres_AddLink_Call{Call: _e.mock.On("AddLink", ctx, link)}
}

func (_c *MockPostgres_AddLink_Call) Run(run func(ctx context.Context, link *domain.Link)) *MockPostgres_AddLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Link
		if args[1] != nil {
			arg1 = args[1].(*domain.Link)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_AddLink_Call) Return(err error) *MockPostgres_AddLink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostgres_AddLink_Call) RunAndReturn(run func(ctx context.Context, link *domain.Link) error) *MockPostgres_AddLink_Call {
	_c.Call.Return(run)
	return _c
}

// AddUserLink provides a mock function for the type MockPostgres
func (_mock *MockPostgres) AddUserLink(ctx context.Context, chatID int64, link *domain.Link) error {
	ret := _mock.Called(ctx, chatID, link)

	if len(ret) == 0 {
		panic("no return value specified for AddUserLink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *domain.Link) error); ok {
		r0 = returnFunc(ctx, chatID, link)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostgres_AddUserLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserLink'
type MockPostgres_AddUserLink_Call struct {
	*mock.Call
}

// AddUserLink is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - link *domain.Link
func (_e *MockPostgres_Expecter) AddUserLink(ctx interface{}, chatID interface{}, link interface{}) *MockPostgres_AddUserLink_Call {
	return &MockPostgres_AddUserLink_Call{Call: _e.mock.On("AddUserLink", ctx, chatID, link)}
}

func (_c *MockPostgres_AddUserLink_Call) Run(run func(ctx context.Context, chatID int64, link *domain.Link)) *MockPostgres_AddUserLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *domain.Link
		if args[2] != nil {
			arg2 = args[2].(*domain.Link)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPostgres_AddUserLink_Call) Return(err error) *MockPostgres_AddUserLink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostgres_AddUserLink_Call) RunAndReturn(run func(ctx context.Context, chatID int64, link *domain.Link) error) *MockPostgres_AddUserLink_Call {
	_c.Call.Return(run)
	return _c
}

// CreateChat provides a mock function for the type MockPostgres
func (_mock *MockPostgres) CreateChat(ctx context.Context, chatID int64) error {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for CreateChat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostgres_CreateChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChat'
type MockPostgres_CreateChat_Call struct {
	*mock.Call
}

// CreateChat is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *MockPostgres_Expecter) CreateChat(ctx interface{}, chatID interface{}) *MockPostgres_CreateChat_Call {
	return &MockPostgres_CreateChat_Call{Call: _e.mock.On("CreateChat", ctx, chatID)}
}

func (_c *MockPostgres_CreateChat_Call) Run(run func(ctx context.Context, chatID int64)) *MockPostgres_CreateChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_CreateChat_Call) Return(err error) *MockPostgres_CreateChat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostgres_CreateChat_Call) RunAndReturn(run func(ctx context.Context, chatID int64) error) *MockPostgres_CreateChat_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteChat provides a mock function for the type MockPostgres
func (_mock *MockPostgres) DeleteChat(ctx context.Context, chatID int64) error {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostgres_DeleteChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteChat'
type MockPostgres_DeleteChat_Call struct {
	*mock.Call
}

// DeleteChat is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *MockPostgres_Expecter) DeleteChat(ctx interface{}, chatID interface{}) *MockPostgres_DeleteChat_Call {
	return &MockPostgres_DeleteChat_Call{Call: _e.mock.On("DeleteChat", ctx, chatID)}
}

func (_c *MockPostgres_DeleteChat_Call) Run(run func(ctx context.Context, chatID int64)) *MockPostgres_DeleteChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_DeleteChat_Call) Return(err error) *MockPostgres_DeleteChat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostgres_DeleteChat_Call) RunAndReturn(run func(ctx context.Context, chatID int64) error) *MockPostgres_DeleteChat_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLink provides a mock function for the type MockPostgres
func (_mock *MockPostgres) DeleteLink(ctx context.Context, link *domain.Link) error {
	ret := _mock.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Link) error); ok {
		r0 = returnFunc(ctx, link)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostgres_DeleteLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLink'
type MockPostgres_DeleteLink_Call struct {
	*mock.Call
}

// DeleteLink is a helper method to define mock.On call
//   - ctx context.Context
//   - link *domain.Link
func (_e *MockPostgres_Expecter) DeleteLink(ctx interface{}, link interface{}) *MockPostgres_DeleteLink_Call {
	return &MockPostgres_DeleteLink_Call{Call: _e.mock.On("DeleteLink", ctx, link)}
}

func (_c *MockPostgres_DeleteLink_Call) Run(run func(ctx context.Context, link *domain.Link)) *MockPostgres_DeleteLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Link
		if args[1] != nil {
			arg1 = args[1].(*domain.Link)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_DeleteLink_Call) Return(err error) *MockPostgres_DeleteLink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostgres_DeleteLink_Call) RunAndReturn(run func(ctx context.Context, link *domain.Link) error) *MockPostgres_DeleteLink_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserLink provides a mock function for the type MockPostgres
func (_mock *MockPostgres) DeleteUserLink(ctx context.Context, chatID int64, alias string) error {
	ret := _mock.Called(ctx, chatID, alias)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserLink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, chatID, alias)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostgres_DeleteUserLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserLink'
type MockPostgres_DeleteUserLink_Call struct {
	*mock.Call
}

// DeleteUserLink is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - alias string
func (_e *MockPostgres_Expecter) DeleteUserLink(ctx interface{}, chatID interface{}, alias interface{}) *MockPostgres_DeleteUserLink_Call {
	return &MockPostgres_DeleteUserLink_Call{Call: _e.mock.On("DeleteUserLink", ctx, chatID, alias)}
}

func (_c *MockPostgres_DeleteUserLink_Call) Run(run func(ctx context.Context, chatID int64, alias string)) *MockPostgres_DeleteUserLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPostgres_DeleteUserLink_Call) Return(err error) *MockPostgres_DeleteUserLink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostgres_DeleteUserLink_Call) RunAndReturn(run func(ctx context.Context, chatID int64, alias string) error) *MockPostgres_DeleteUserLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinkByURL provides a mock function for the type MockPostgres
func (_mock *MockPostgres) GetLinkByURL(ctx context.Context, url string) (*domain.Link, error) {
	ret := _mock.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkByURL")
	}

	var r0 *domain.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Link, error)); ok {
		return returnFunc(ctx, url)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Link); ok {
		r0 = returnFunc(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Link)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostgres_GetLinkByURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinkByURL'
type MockPostgres_GetLinkByURL_Call struct {
	*mock.Call
}

// GetLinkByURL is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockPostgres_Expecter) GetLinkByURL(ctx interface{}, url interface{}) *MockPostgres_GetLinkByURL_Call {
	return &MockPostgres_GetLinkByURL_Call{Call: _e.mock.On("GetLinkByURL", ctx, url)}
}

func (_c *MockPostgres_GetLinkByURL_Call) Run(run func(ctx context.Context, url string)) *MockPostgres_GetLinkByURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_GetLinkByURL_Call) Return(link *domain.Link, err error) *MockPostgres_GetLinkByURL_Call {
	_c.Call.Return(link, err)
	return _c
}

func (_c *MockPostgres_GetLinkByURL_Call) RunAndReturn(run func(ctx context.Context, url string) (*domain.Link, error)) *MockPostgres_GetLinkByURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinks provides a mock function for the type MockPostgres
func (_mock *MockPostgres) GetLinks(ctx context.Context, limit uint64, offset uint64) ([]domain.Link, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetLinks")
	}

	var r0 []domain.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) ([]domain.Link, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, uint64) []domain.Link); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Link)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostgres_GetLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinks'
type MockPostgres_GetLinks_Call struct {
	*mock.Call
}

// GetLinks is a helper method to define mock.On call
//   - ctx context.Context
//   - limit uint64
//   - offset uint64
func (_e *MockPostgres_Expecter) GetLinks(ctx interface{}, limit interface{}, offset interface{}) *MockPostgres_GetLinks_Call {
	return &MockPostgres_GetLinks_Call{Call: _e.mock.On("GetLinks", ctx, limit, offset)}
}

func (_c *MockPostgres_GetLinks_Call) Run(run func(ctx context.Context, limit uint64, offset uint64)) *MockPostgres_GetLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPostgres_GetLinks_Call) Return(links []domain.Link, err error) *MockPostgres_GetLinks_Call {
	_c.Call.Return(links, err)
	return _c
}

func (_c *MockPostgres_GetLinks_Call) RunAndReturn(run func(ctx context.Context, limit uint64, offset uint64) ([]domain.Link, error)) *MockPostgres_GetLinks_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinksByChatID provides a mock function for the type MockPostgres
func (_mock *MockPostgres) GetLinksByChatID(ctx context.Context, chatID int64) ([]domain.Link, error) {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetLinksByChatID")
	}

	var r0 []domain.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]domain.Link, error)); ok {
		return returnFunc(ctx, chatID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []domain.Link); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Link)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostgres_GetLinksByChatID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinksByChatID'
type MockPostgres_GetLinksByChatID_Call struct {
	*mock.Call
}

// GetLinksByChatID is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *MockPostgres_Expecter) GetLinksByChatID(ctx interface{}, chatID interface{}) *MockPostgres_GetLinksByChatID_Call {
	return &MockPostgres_GetLinksByChatID_Call{Call: _e.mock.On("GetLinksByChatID", ctx, chatID)}
}

func (_c *MockPostgres_GetLinksByChatID_Call) Run(run func(ctx context.Context, chatID int64)) *MockPostgres_GetLinksByChatID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_GetLinksByChatID_Call) Return(links []domain.Link, err error) *MockPostgres_GetLinksByChatID_Call {
	_c.Call.Return(links, err)
	return _c
}

func (_c *MockPostgres_GetLinksByChatID_Call) RunAndReturn(run func(ctx context.Context, chatID int64) ([]domain.Link, error)) *MockPostgres_GetLinksByChatID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserLinksByTag provides a mock function for the type MockPostgres
func (_mock *MockPostgres) GetUserLinksByTag(ctx context.Context, chatID int64, tags string) ([]*domain.Link, error) {
	ret := _mock.Called(ctx, chatID, tags)

	if len(ret) == 0 {
		panic("no return value specified for GetUserLinksByTag")
	}

	var r0 []*domain.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) ([]*domain.Link, error)); ok {
		return returnFunc(ctx, chatID, tags)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) []*domain.Link); ok {
		r0 = returnFunc(ctx, chatID, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Link)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, chatID, tags)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostgres_GetUserLinksByTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserLinksByTag'
type MockPostgres_GetUserLinksByTag_Call struct {
	*mock.Call
}

// GetUserLinksByTag is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - tags string
func (_e *MockPostgres_Expecter) GetUserLinksByTag(ctx interface{}, chatID interface{}, tags interface{}) *MockPostgres_GetUserLinksByTag_Call {
	return &MockPostgres_GetUserLinksByTag_Call{Call: _e.mock.On("GetUserLinksByTag", ctx, chatID, tags)}
}

func (_c *MockPostgres_GetUserLinksByTag_Call) Run(run func(ctx context.Context, chatID int64, tags string)) *MockPostgres_GetUserLinksByTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPostgres_GetUserLinksByTag_Call) Return(links []*domain.Link, err error) *MockPostgres_GetUserLinksByTag_Call {
	_c.Call.Return(links, err)
	return _c
}

func (_c *MockPostgres_GetUserLinksByTag_Call) RunAndReturn(run func(ctx context.Context, chatID int64, tags string) ([]*domain.Link, error)) *MockPostgres_GetUserLinksByTag_Call {
	_c.Call.Return(run)
	return _c
}

// IsLinkExists provides a mock function for the type MockPostgres
func (_mock *MockPostgres) IsLinkExists(ctx context.Context, url string) (bool, error) {
	ret := _mock.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for IsLinkExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, url)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, url)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostgres_IsLinkExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsLinkExists'
type MockPostgres_IsLinkExists_Call struct {
	*mock.Call
}

// IsLinkExists is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockPostgres_Expecter) IsLinkExists(ctx interface{}, url interface{}) *MockPostgres_IsLinkExists_Call {
	return &MockPostgres_IsLinkExists_Call{Call: _e.mock.On("IsLinkExists", ctx, url)}
}

func (_c *MockPostgres_IsLinkExists_Call) Run(run func(ctx context.Context, url string)) *MockPostgres_IsLinkExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostgres_IsLinkExists_Call) Return(b bool, err error) *MockPostgres_IsLinkExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPostgres_IsLinkExists_Call) RunAndReturn(run func(ctx context.Context, url string) (bool, error)) *MockPostgres_IsLinkExists_Call {
	_c.Call.Return(run)
	return _c
}

// IsUserLinkExists provides a mock function for the type MockPostgres
func (_mock *MockPostgres) IsUserLinkExists(ctx context.Context, alias string, chatID int64) (bool, error) {
	ret := _mock.Called(ctx, alias, chatID)

	if len(ret) == 0 {
		panic("no return value specified for IsUserLinkExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (bool, error)); ok {
		return returnFunc(ctx, alias, chatID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) bool); ok {
		r0 = returnFunc(ctx, alias, chatID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = returnFunc(ctx, alias, chatID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostgres_IsUserLinkExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUserLinkExists'
type MockPostgres_IsUserLinkExists_Call struct {
	*mock.Call
}

// IsUserLinkExists is a helper method to define mock.On call
//   - ctx context.Context
//   - alias string
//   - chatID int64
func (_e *MockPostgres_Expecter) IsUserLinkExists(ctx interface{}, alias interface{}, chatID interface{}) *MockPostgres_IsUserLinkExists_Call {
	return &MockPostgres_IsUserLinkExists_Call{Call: _e.mock.On("IsUserLinkExists", ctx, alias, chatID)}
}

func (_c *MockPostgres_IsUserLinkExists_Call) Run(run func(ctx context.Context, alias string, chatID int64)) *MockPostgres_IsUserLinkExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPostgres_IsUserLinkExists_Call) Return(b bool, err error) *MockPostgres_IsUserLinkExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockPostgres_IsUserLinkExists_Call) RunAndReturn(run func(ctx context.Context, alias string, chatID int64) (bool, error)) *MockPostgres_IsUserLinkExists_Call {
	_c.Call.Return(run)
	return _c
}
