// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"context"
	"linktracker/internal/domain"
	"linktracker/internal/storage"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// GetTempUserLinks provides a mock function for the type MockStorage
func (_mock *MockStorage) GetTempUserLinks(ctx context.Context, userID int64) (*storage.TempUserLinks, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTempUserLinks")
	}

	var r0 *storage.TempUserLinks
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*storage.TempUserLinks, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *storage.TempUserLinks); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.TempUserLinks)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetTempUserLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTempUserLinks'
type MockStorage_GetTempUserLinks_Call struct {
	*mock.Call
}

// GetTempUserLinks is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockStorage_Expecter) GetTempUserLinks(ctx interface{}, userID interface{}) *MockStorage_GetTempUserLinks_Call {
	return &MockStorage_GetTempUserLinks_Call{Call: _e.mock.On("GetTempUserLinks", ctx, userID)}
}

func (_c *MockStorage_GetTempUserLinks_Call) Run(run func(ctx context.Context, userID int64)) *MockStorage_GetTempUserLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_GetTempUserLinks_Call) Return(tempUserLinks *storage.TempUserLinks, err error) *MockStorage_GetTempUserLinks_Call {
	_c.Call.Return(tempUserLinks, err)
	return _c
}

func (_c *MockStorage_GetTempUserLinks_Call) RunAndReturn(run func(ctx context.Context, userID int64) (*storage.TempUserLinks, error)) *MockStorage_GetTempUserLinks_Call {
	_c.Call.Return(run)
	return _c
}

// GetTempUserState provides a mock function for the type MockStorage
func (_mock *MockStorage) GetTempUserState(ctx context.Context, userID int64) (*domain.UserStateInfo, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTempUserState")
	}

	var r0 *domain.UserStateInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.UserStateInfo, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.UserStateInfo); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserStateInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_GetTempUserState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTempUserState'
type MockStorage_GetTempUserState_Call struct {
	*mock.Call
}

// GetTempUserState is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockStorage_Expecter) GetTempUserState(ctx interface{}, userID interface{}) *MockStorage_GetTempUserState_Call {
	return &MockStorage_GetTempUserState_Call{Call: _e.mock.On("GetTempUserState", ctx, userID)}
}

func (_c *MockStorage_GetTempUserState_Call) Run(run func(ctx context.Context, userID int64)) *MockStorage_GetTempUserState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_GetTempUserState_Call) Return(userStateInfo *domain.UserStateInfo, err error) *MockStorage_GetTempUserState_Call {
	_c.Call.Return(userStateInfo, err)
	return _c
}

func (_c *MockStorage_GetTempUserState_Call) RunAndReturn(run func(ctx context.Context, userID int64) (*domain.UserStateInfo, error)) *MockStorage_GetTempUserState_Call {
	_c.Call.Return(run)
	return _c
}

// SaveTempUserLinks provides a mock function for the type MockStorage
func (_mock *MockStorage) SaveTempUserLinks(ctx context.Context, tempUserLinks *storage.TempUserLinks) error {
	ret := _mock.Called(ctx, tempUserLinks)

	if len(ret) == 0 {
		panic("no return value specified for SaveTempUserLinks")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *storage.TempUserLinks) error); ok {
		r0 = returnFunc(ctx, tempUserLinks)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_SaveTempUserLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTempUserLinks'
type MockStorage_SaveTempUserLinks_Call struct {
	*mock.Call
}

// SaveTempUserLinks is a helper method to define mock.On call
//   - ctx context.Context
//   - tempUserLinks *storage.TempUserLinks
func (_e *MockStorage_Expecter) SaveTempUserLinks(ctx interface{}, tempUserLinks interface{}) *MockStorage_SaveTempUserLinks_Call {
	return &MockStorage_SaveTempUserLinks_Call{Call: _e.mock.On("SaveTempUserLinks", ctx, tempUserLinks)}
}

func (_c *MockStorage_SaveTempUserLinks_Call) Run(run func(ctx context.Context, tempUserLinks *storage.TempUserLinks)) *MockStorage_SaveTempUserLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *storage.TempUserLinks
		if args[1] != nil {
			arg1 = args[1].(*storage.TempUserLinks)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_SaveTempUserLinks_Call) Return(err error) *MockStorage_SaveTempUserLinks_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_SaveTempUserLinks_Call) RunAndReturn(run func(ctx context.Context, tempUserLinks *storage.TempUserLinks) error) *MockStorage_SaveTempUserLinks_Call {
	_c.Call.Return(run)
	return _c
}

// SetTempUserState provides a mock function for the type MockStorage
func (_mock *MockStorage) SetTempUserState(ctx context.Context, userInfo *domain.UserStateInfo) error {
	ret := _mock.Called(ctx, userInfo)

	if len(ret) == 0 {
		panic("no return value specified for SetTempUserState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.UserStateInfo) error); ok {
		r0 = returnFunc(ctx, userInfo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorage_SetTempUserState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTempUserState'
type MockStorage_SetTempUserState_Call struct {
	*mock.Call
}

// SetTempUserState is a helper method to define mock.On call
//   - ctx context.Context
//   - userInfo *domain.UserStateInfo
func (_e *MockStorage_Expecter) SetTempUserState(ctx interface{}, userInfo interface{}) *MockStorage_SetTempUserState_Call {
	return &MockStorage_SetTempUserState_Call{Call: _e.mock.On("SetTempUserState", ctx, userInfo)}
}

func (_c *MockStorage_SetTempUserState_Call) Run(run func(ctx context.Context, userInfo *domain.UserStateInfo)) *MockStorage_SetTempUserState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.UserStateInfo
		if args[1] != nil {
			arg1 = args[1].(*domain.UserStateInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_SetTempUserState_Call) Return(err error) *MockStorage_SetTempUserState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorage_SetTempUserState_Call) RunAndReturn(run func(ctx context.Context, userInfo *domain.UserStateInfo) error) *MockStorage_SetTempUserState_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScrapperClient creates a new instance of MockScrapperClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScrapperClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScrapperClient {
	mock := &MockScrapperClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScrapperClient is an autogenerated mock type for the scrapperClient type
type MockScrapperClient struct {
	mock.Mock
}

type MockScrapperClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScrapperClient) EXPECT() *MockScrapperClient_Expecter {
	return &MockScrapperClient_Expecter{mock: &_m.Mock}
}

// AddLink provides a mock function for the type MockScrapperClient
func (_mock *MockScrapperClient) AddLink(ctx context.Context, chatID int64, link *domain.Link) error {
	ret := _mock.Called(ctx, chatID, link)

	if len(ret) == 0 {
		panic("no return value specified for AddLink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, domain.Link) error); ok {
		r0 = returnFunc(ctx, chatID, *link)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockScrapperClient_AddLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddLink'
type MockScrapperClient_AddLink_Call struct {
	*mock.Call
}

// AddLink is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - link domain.Link
func (_e *MockScrapperClient_Expecter) AddLink(ctx interface{}, chatID interface{}, link interface{}) *MockScrapperClient_AddLink_Call {
	return &MockScrapperClient_AddLink_Call{Call: _e.mock.On("AddLink", ctx, chatID, link)}
}

func (_c *MockScrapperClient_AddLink_Call) Run(run func(ctx context.Context, chatID int64, link domain.Link)) *MockScrapperClient_AddLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 domain.Link
		if args[2] != nil {
			arg2 = args[2].(domain.Link)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockScrapperClient_AddLink_Call) Return(err error) *MockScrapperClient_AddLink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockScrapperClient_AddLink_Call) RunAndReturn(run func(ctx context.Context, chatID int64, link domain.Link) error) *MockScrapperClient_AddLink_Call {
	_c.Call.Return(run)
	return _c
}

// CreateChat provides a mock function for the type MockScrapperClient
func (_mock *MockScrapperClient) CreateChat(ctx context.Context, chatID int64) error {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for CreateChat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockScrapperClient_CreateChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChat'
type MockScrapperClient_CreateChat_Call struct {
	*mock.Call
}

// CreateChat is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *MockScrapperClient_Expecter) CreateChat(ctx interface{}, chatID interface{}) *MockScrapperClient_CreateChat_Call {
	return &MockScrapperClient_CreateChat_Call{Call: _e.mock.On("CreateChat", ctx, chatID)}
}

func (_c *MockScrapperClient_CreateChat_Call) Run(run func(ctx context.Context, chatID int64)) *MockScrapperClient_CreateChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScrapperClient_CreateChat_Call) Return(err error) *MockScrapperClient_CreateChat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockScrapperClient_CreateChat_Call) RunAndReturn(run func(ctx context.Context, chatID int64) error) *MockScrapperClient_CreateChat_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteChat provides a mock function for the type MockScrapperClient
func (_mock *MockScrapperClient) DeleteChat(ctx context.Context, chatID int64) error {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockScrapperClient_DeleteChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteChat'
type MockScrapperClient_DeleteChat_Call struct {
	*mock.Call
}

// DeleteChat is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *MockScrapperClient_Expecter) DeleteChat(ctx interface{}, chatID interface{}) *MockScrapperClient_DeleteChat_Call {
	return &MockScrapperClient_DeleteChat_Call{Call: _e.mock.On("DeleteChat", ctx, chatID)}
}

func (_c *MockScrapperClient_DeleteChat_Call) Run(run func(ctx context.Context, chatID int64)) *MockScrapperClient_DeleteChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScrapperClient_DeleteChat_Call) Return(err error) *MockScrapperClient_DeleteChat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockScrapperClient_DeleteChat_Call) RunAndReturn(run func(ctx context.Context, chatID int64) error) *MockScrapperClient_DeleteChat_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLink provides a mock function for the type MockScrapperClient
func (_mock *MockScrapperClient) DeleteLink(ctx context.Context, chatID int64, alias string) error {
	ret := _mock.Called(ctx, chatID, alias)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLink")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, chatID, alias)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockScrapperClient_DeleteLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLink'
type MockScrapperClient_DeleteLink_Call struct {
	*mock.Call
}

// DeleteLink is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - alias string
func (_e *MockScrapperClient_Expecter) DeleteLink(ctx interface{}, chatID interface{}, alias interface{}) *MockScrapperClient_DeleteLink_Call {
	return &MockScrapperClient_DeleteLink_Call{Call: _e.mock.On("DeleteLink", ctx, chatID, alias)}
}

func (_c *MockScrapperClient_DeleteLink_Call) Run(run func(ctx context.Context, chatID int64, alias string)) *MockScrapperClient_DeleteLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockScrapperClient_DeleteLink_Call) Return(err error) *MockScrapperClient_DeleteLink_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockScrapperClient_DeleteLink_Call) RunAndReturn(run func(ctx context.Context, chatID int64, alias string) error) *MockScrapperClient_DeleteLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilteredLinks provides a mock function for the type MockScrapperClient
func (_mock *MockScrapperClient) GetFilteredLinks(ctx context.Context, chatID int64, tag string) ([]*domain.Link, error) {
	ret := _mock.Called(ctx, chatID, tag)

	if len(ret) == 0 {
		panic("no return value specified for GetFilteredLinks")
	}

	var r0 []*domain.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) ([]*domain.Link, error)); ok {
		return returnFunc(ctx, chatID, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) []*domain.Link); ok {
		r0 = returnFunc(ctx, chatID, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Link)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, chatID, tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScrapperClient_GetFilteredLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilteredLinks'
type MockScrapperClient_GetFilteredLinks_Call struct {
	*mock.Call
}

// GetFilteredLinks is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - tag string
func (_e *MockScrapperClient_Expecter) GetFilteredLinks(ctx interface{}, chatID interface{}, tag interface{}) *MockScrapperClient_GetFilteredLinks_Call {
	return &MockScrapperClient_GetFilteredLinks_Call{Call: _e.mock.On("GetFilteredLinks", ctx, chatID, tag)}
}

func (_c *MockScrapperClient_GetFilteredLinks_Call) Run(run func(ctx context.Context, chatID int64, tag string)) *MockScrapperClient_GetFilteredLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockScrapperClient_GetFilteredLinks_Call) Return(links []*domain.Link, err error) *MockScrapperClient_GetFilteredLinks_Call {
	_c.Call.Return(links, err)
	return _c
}

func (_c *MockScrapperClient_GetFilteredLinks_Call) RunAndReturn(run func(ctx context.Context, chatID int64, tag string) ([]*domain.Link, error)) *MockScrapperClient_GetFilteredLinks_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinks provides a mock function for the type MockScrapperClient
func (_mock *MockScrapperClient) GetLinks(ctx context.Context, chatID int64) ([]*domain.Link, error) {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetLinks")
	}

	var r0 []*domain.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]*domain.Link, error)); ok {
		return returnFunc(ctx, chatID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []*domain.Link); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Link)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScrapperClient_GetLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinks'
type MockScrapperClient_GetLinks_Call struct {
	*mock.Call
}

// GetLinks is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *MockScrapperClient_Expecter) GetLinks(ctx interface{}, chatID interface{}) *MockScrapperClient_GetLinks_Call {
	return &MockScrapperClient_GetLinks_Call{Call: _e.mock.On("GetLinks", ctx, chatID)}
}

func (_c *MockScrapperClient_GetLinks_Call) Run(run func(ctx context.Context, chatID int64)) *MockScrapperClient_GetLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScrapperClient_GetLinks_Call) Return(links []*domain.Link, err error) *MockScrapperClient_GetLinks_Call {
	_c.Call.Return(links, err)
	return _c
}

func (_c *MockScrapperClient_GetLinks_Call) RunAndReturn(run func(ctx context.Context, chatID int64) ([]*domain.Link, error)) *MockScrapperClient_GetLinks_Call {
	_c.Call.Return(run)
	return _c
}
